### ISSUE TITLE
Syntax when searching PDFs

### ISSUE THREAD

**Issue by AtomicNess123** [karlicoss/dotfiles-emacs#2]
Hi,

What would be the syntax in args (my/search) to search within PDFs?
`  :rg-opts '( "--no-hidden")))`

I'm trying to implement this into your function since I have lots of Mendeley PDFs where I would like to search: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#preprocessor. In the Terminal this would look like

`rg --pre ./preprocess 'The Commentz-Walter algorithm' 1995-watson.pdf`

But no idea how it would look in emacs.
Thanks, 
GM

**Comment by karlicoss** [comment]
Hey, haven't used it, so not sure how it's actually working.. Is it meant to search over single PDF or a directory of PDFs? In either case, it's possible that you'd rather benefit from making a copy of `my/search` and having a separate function for PDF search. You can try setting `:rg-opts '("--pre" "/full/absolute/path/to/preprocess")`, but not sure if it would work straightaway.

You also mentioned rga [here](https://github.com/karlicoss/promnesia/issues/74#issuecomment-628184548), I haven't set up integration with it yet (although I want at some point), but I think it's better suited than custom preprocessors.
Looks like [someone](https://github.com/phiresky/ripgrep-all/issues/34#issuecomment-555801958) used it with helm-ag, so perhaps you could use their approach (or even do that in helm-rg).

**Comment by AtomicNess123** [comment]
Over both single files and folders. I think what you suggest is a good idea, although my notes are both a mixture of PDFs and simple text, so it would be handy to search on all types of documents. I'm glad to hear that you plan on intergating with rga. Thanks again.
